# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $resourcesByGroup := dict }}
{{- range .Values.policies }}
  {{- $group := .resource.group | default "" }}
  {{- $kind := .resource.kind | lower }}
  {{- $resource := printf "%ss" $kind }}
  {{- $existing := index $resourcesByGroup $group | default list }}
  {{- if not (has $resource $existing) }}
    {{- $updated := append $existing $resource }}
    {{- $_ := set $resourcesByGroup $group $updated }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-object-monitor.fullname" . }}
  labels:
    {{- include "kubernetes-object-monitor.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  # This loop automatically generates rules for all resources defined in your policies.
  {{- range $group, $resources := $resourcesByGroup }}
  {{- /* Skip nodes in core group since we already added it above */}}
  {{- $filteredResources := list }}
  {{- range $resources }}
    {{- if not (and (eq $group "") (eq . "nodes")) }}
      {{- $filteredResources = append $filteredResources . }}
    {{- end }}
  {{- end }}
  {{- if $filteredResources }}
  - apiGroups:
      - {{ $group | quote }}
    resources:
      {{- range $filteredResources }}
      - {{ . }}
      {{- end }}
    verbs:
      - get
      - list
      - watch
  {{- end }}
  {{- end }}
